language: python

python:
  - "2.6"
  - "2.7"

install:
  - pip install --upgrade pip  --use-mirrors
  - pip install coveralls --use-mirrors
  - pip install .

script:
  - coverage run --source=workflow setup.py test

after_success:
  - coveralls

notifications:
  email: false
